[versions]
#config
compileSdk = "33"
minSdk = "26"
targetSdk = "33"
versionCode = "1"
versionName = "0.0.1"

#plugins
coreKtx = "1.9.0"
gradle = "7.4.2"
kotlin = "1.8.10"

#libs
appCompat = "1.6.1"
compose-activity = "1.6.1"
compose-compiler = "1.4.3"
compose-foundation = "1.3.1"
compose-icons = "1.3.1"
compose-material = "1.3.1"
compose-ui = "1.3.3"
compose-ui-preview = "1.3.3"
compose-viewModel = "2.5.1"
dagger = "2.45"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-icons" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui-preview" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewModel" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
